services:
  app:
    container_name: "glpi"
    build:
      context: "./docker/app"
    restart: "unless-stopped"
    volumes:
      - ".:/var/www/glpi:rw"
    ports:
      - "8080:80"

  mysql:
    image: 'mysql:8.0'
    volumes:
      - './docker/mysql:/var/lib/mysql'
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password

  phpmyadmin:
    image: 'phpmyadmin:5.2.1'
    ports:
      - '8085:80'
    environment:
      - 'PMA_HOST=mysql'
      - 'UPLOAD_LIMIT=102400K'